frontend:
	bash  components/frontend.sh

mongodb:	
	bash  components/mongodb.sh

catalogue:	
	bash  components/catalogue.sh

redish:	
	bash  components/redish.sh

user:	
	bash  components/user.sh

cart:
	bash components/cart.sh